# Generated by Django 5.0.1 on 2024-01-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
        migrations.AlterModelTable(
            name='accounts',
            table='Accounts',
        ),
    ]
